import Head from 'next/head'
import Link from "next/link";
import styles from '/styles/homePage.module.scss'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Learning NextJS</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
           <div className={styles.container}>
               <div className={styles.item}>
                   <Link href={'/elements'}>Компоненты</Link>
               </div>
               <div className={styles.item}>
                   <Link href={`/tests/`}>Тесты</Link>
               </div>
           </div>
        </div>
    )
}
